language: racket
sudo: false
dist: trusty

env:
  global:
  - RACKET_DIR=~/racket
  matrix:
  - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

addons:
  ssh_known_hosts: junkfood.cs.umd.edu

before_deploy:
  - openssl aes-256-cbc -K $encrypted_71c99aa46c45_key -iv $encrypted_71c99aa46c45_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git clone https://gist.github.com/815bdda5cfcdee18d480cb6a5d1119f3.git racket-tweet


install: 
before_script: 

script:
  - make

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/www/ dvanhorn@junkfood.cs.umd.edu:www/; racket -e "(require \"racket-tweet/tweet.rkt\") (tweet! \"I\'m tweeting from Racket from Travis CI, triggered by a push to Github. https://github.com/plum-umd/dvanhorn\")"
    on:
      branch: master
