on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install Racket
      uses: Bogdanp/setup-racket@v0.10
      with:
	architecture: 'x64'
	distribution: 'full'
	version: '7.9'
    - name: Run Tests
      run: raco test .
