on:
  - push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.15
      with:
        architecture: 'x64'
        distribution: 'full'
        version: '7.9'
    - name: Run Tests
      run: raco test .
    - name: Archive www
      uses: actions/upload-artifact@v4
      with:
        name: www
        path: www
