on:
  - push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install Racket
      uses: Bogdanp/setup-racket@v0.10
      with:
        architecture: 'x64'
        distribution: 'full'
        version: '7.9'
    - name: Run Tests
      run: raco test .
  deploy:
    needs: build-and-test    
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to web
      uses: plum-umd/github-actions-rsync@master
      with:
        RSYNC_OPTIONS: -r --delete-after --quiet
        RSYNC_TARGET: www/
        RSYNC_SOURCE: www/
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_USERNAME: ${{secrets.SSH_USERNAME}}
        SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}
